server:
  port: 8080
  tomcat:
    max-swallow-size: 50MB
    max-http-form-post-size: 50MB

spring:
  application:
    name: du-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/gwlweb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo&characterEncoding=utf-8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 100MB
  kafka:
    bootstrap-servers: 3.112.54.245:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: timeline-group
      properties:
        spring.json.trusted.packages: "*"

springdoc:
  swagger-ui:
    persistAuthorization: true

dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://3.112.54.245:2181

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: gwl.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
aws:
  region: ap-northeast-1
  accessKey: AKIAQIX273TDK6JUORMS
  secretKey: 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
  s3:
    avatar: arn:aws:s3:ap-northeast-1:018779987142:accesspoint/access1
  
